server:
  port: 5406

spring:
  application:
    name: microservice-catalog


  datasource:
    url: jdbc:postgresql://localhost:5433/catalog_vetly
    username: postgres
    password: root
    drive-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:5401/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
