server:
  port: ${PORT:5401}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    # Usamos la variable de Railway o caemos en localhost para desarrollo local
    hostname: ${RAILWAY_PUBLIC_DOMAIN:localhost}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # Si estamos en Railway, usamos la URL pública; si no, localhost
      defaultZone: ${EUREKA_URL:http://localhost:5401/eureka/}