server:
  port: 5401

spring:
  application:
    name: microservice-eureka
  config:
    import: optional:configserver:http://localhost:8888


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-register: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/
